default_context:
  project_name: InvenioRDM Demo Site
  project_shortname: demo-inveniordm
  project_site: inveniordm.web.cern.ch
  github_repo: inveniosoftware/demo-inveniordm
  description: InvenioRDM Demo Instance
  author_name: CERN
  author_email: info@inveniosoftware.org
  year: 2022
  python_version: "3.9"
  database: postgresql
  search: opensearch2
  file_storage: "s3"
  development_tools: no
