#!/usr/bin/env bash

# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
#
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
# Copyright (C) 2025 KTH Royal Institute of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

cd ${PROJECTDIR}
uv_lock_path="./uv.lock"

if [ ! -f $uv_lock_path ]; then
    echo "'uv.lock' not found. Generating via 'uv lock'..."
    uv lock
fi

# Install all dependency groups so check-manifest is available
uv sync --all-groups
export INVENIO_WEBPACKEXT_NPM_PKG_CLS=pynpm:PNPMPackage
# Build assets
INVENIO_LOCAL_INSTANCE_PATH=$(uv run invenio shell --no-term-title -c "print(app.instance_path)")
cp -r ./static/. ${INVENIO_LOCAL_INSTANCE_PATH}/static/
cp -r ./assets/. ${INVENIO_LOCAL_INSTANCE_PATH}/assets/

uv run invenio collect -v
uv run invenio webpack buildall
