#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2019 CERN.
# SPDX-FileCopyrightText: 2019 Northwestern University.
# Copyright (C) 2025 KTH Royal Institute of Technology.
# SPDX-License-Identifier: MIT

set -e

cd "${PROJECTDIR}"

export FLASK_ENV=development
export INVENIO_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@localhost/{{cookiecutter.project_shortname}}"

# Start Worker and Server
uv run celery -A invenio_app.celery worker -l INFO & pid_celery=$!

uv run invenio run \
       --cert "${script_path}/../docker/nginx/test.crt" \
       --key "${script_path}/../docker/nginx/test.key" & pid_server=$!

trap 'kill "${pid_celery}" "${pid_server}" &>/dev/null' EXIT

wait "${pid_celery}" "${pid_server}"
