#!/usr/bin/env bash

# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
#
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
# Copyright (C) 2025 KTH Royal Institute of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

cd ${PROJECTDIR}

export FLASK_ENV=development
export INVENIO_SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@localhost/{{cookiecutter.project_shortname}}"

# Start Worker and Server
uv run celery -A invenio_app.celery worker -l INFO & pid_celery=$!

uv run invenio run \
       --cert "$script_path"/../docker/nginx/test.crt \
       --key "$script_path"/../docker/nginx/test.key & pid_server=$!

trap 'kill $pid_celery $pid_server &>/dev/null' EXIT

wait $pid_celery $pid_server
