#!/usr/bin/env bash

# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
#
# Copyright (C) 2019 CERN.
# Copyright (C) 2019 Northwestern University.
# Copyright (C) 2021 Esteban J. G. Gabancho.
# Copyright (C) 2025 KTH Royal Institute of Technology.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

cd ${PROJECTDIR}

# Clean redis
uv run invenio shell --no-term-title -c "import redis; redis.StrictRedis.from_url(app.config['CACHE_REDIS_URL']).flushall(); print('Cache cleared')"
uv run invenio db destroy --yes-i-know
uv run invenio db init create
uv run invenio index destroy --force --yes-i-know
uv run invenio index init --force
uv run invenio index queue init purge
if [ $COOKIECUTTER_FILE_STORAGE -eq "S3" ]
then
uv run invenio files location s3-default s3://default --default
else
uv run invenio files location --default 'default-location'  $(uv run invenio shell --no-term-title -c "print(app.instance_path)")
fi

# Create admin role to rectict access
uv run invenio roles create admin
uv run invenio access allow superuser-access role admin
