version: '2.2'
services:
  app:
    build:
      context: ./
      args:
        - ENVIRONMENT=DEV
    image: {{cookiecutter.project_shortname}}
    restart: "unless-stopped"
    environment:
      - "INVENIO_ACCOUNTS_SESSION_REDIS_URL=redis://cache:6379/1"
      - "INVENIO_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CACHE_REDIS_URL=redis://cache:6379/0"
      - "INVENIO_CACHE_TYPE=redis"
      - "INVENIO_CELERY_BROKER_URL=amqp://guest:guest@mq:5672/"
      - "INVENIO_CELERY_RESULT_BACKEND=redis://cache:6379/2"
      - "INVENIO_SEARCH_ELASTIC_HOSTS=['es:9200']"
      - "INVENIO_SECRET_KEY=CHANGE_ME"
      {%- if cookiecutter.database == 'postgresql'%}
      - "INVENIO_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@db/{{cookiecutter.project_shortname}}"
      {%- elif cookiecutter.database == 'mysql'%}
      - "INVENIO_SQLALCHEMY_DATABASE_URI=mysql+pymysql://{{cookiecutter.project_shortname}}:{{cookiecutter.project_shortname}}@db/{{cookiecutter.project_shortname}}"
      {%- endif %}
      - "INVENIO_WSGI_PROXIES=2"
      - "INVENIO_RATELIMIT_STORAGE_URL=redis://cache:6379/3"
  frontend:
    build: ./docker/nginx/
    image: {{cookiecutter.project_shortname}}-frontend
    restart: "unless-stopped"
    ports:
      - "80"
      - "443"
  cache:
    image: redis
    restart: "unless-stopped"
    read_only: true
    ports:
      - "6379:6379"
  db:
    {%- if cookiecutter.database == 'postgresql'%}
    image: postgres:12.4
    restart: "unless-stopped"
    environment:
      - "POSTGRES_USER={{cookiecutter.project_shortname}}"
      - "POSTGRES_PASSWORD={{cookiecutter.project_shortname}}"
      - "POSTGRES_DB={{cookiecutter.project_shortname}}"
    ports:
      - "5432:5432"
    {%- elif cookiecutter.database == 'mysql'%}
    image: mysql
    restart: "unless-stopped"
    environment:
      - "MYSQL_ROOT_PASSWORD={{cookiecutter.project_shortname}}"
      - "MYSQL_DATABAE={{cookiecutter.project_shortname}}"
      - "MYSQL_USER={{cookiecutter.project_shortname}}"
      - "MYSQL_PASSWORD={{cookiecutter.project_shortname}}"
    ports:
      - "3306:3306"
    {%- endif %}
  mq:
    image: rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
  es:
    {%- if cookiecutter.elasticsearch == '7' %}
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    {%- elif cookiecutter.elasticsearch == '6' %}
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.9
    {%- endif %}
    restart: "unless-stopped"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:9200/_cluster/health?wait_for_status=green"]
      interval: 30s
      timeout: 30s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
{%- if cookiecutter.file_storage == 'S3'%}
  s3:
    image: minio/minio
    restart: "unless-stopped"
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: CHANGE_ME
      MINIO_SECRET_KEY: CHANGE_ME
    volumes:
      - data:/data
    command: server /data
{%- endif %}
