name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./invenio-rdm/Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/invenio-rdm
            context: ./invenio-rdm/
          - dockerfile: ./invenio-rdm/docker/nginx/Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/invenio-rdm-nginx
            context: ./invenio-rdm/docker/nginx/
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Run Trivy static code analysis
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy static code analysis results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'fs'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 

      - name: Setup files and folders using cookiecutter
        run: |
          python -m pip install --upgrade pipenv cookiecutter
          cookiecutter gh:front-matter/cookiecutter-invenio-rdm --no-input --config-file ./.github/default-config.yml
          cd invenio-rdm
          pipenv lock

      - name: Build an image from Dockerfile
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/invenio-rdm:${{ github.sha }} ./almalinux/

      - name: Run Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/invenio-rdm:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'image'
          
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
          flavor: |
            latest=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.1.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          