name: Release
on:
  push:
    branches:
      - "master"
# on:
#   release:
#     types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Setup files and folders using cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter
          cookiecutter gh:front-matter/cookiecutter-invenio-rdm --no-input --config-file ./.github/default-config.yml
          ls -l demo-inveniordm
      # - name: Generate Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ matrix.image }}
      #     tags: |
      #       type=ref,event=branch
      #       type=semver,pattern={{version}}
      #     flavor: |
      #       latest=true
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2.1.0
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2.1.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Push to GitHub Packages
      #   uses: docker/build-push-action@v3.2.0
      #   with:
      #     context: ${{ matrix.context }}
      #     file: ${{ matrix.dockerfile }}
      #     platforms: linux/amd64, linux/arm64
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
          